### ISSUE TITLE
Suggestion: Unix time generator

### ISSUE THREAD

**Issue by daniel-shuy** [Thomas-Negrault/dev-tools#6]
Just discovered this tool today, really appreciate it! Would be great if it also had a tool to generate the current Unix time, eg. something like https://www.epochconverter.com/. A Unix time converter would be icing on the top!

**Comment by thmsbernard** [comment]
Thank you for the suggestion ! I added a new tool at: https://devtools.best/epoch-timestamp-converter
![image](https://user-images.githubusercontent.com/6841201/108436610-01e81500-724c-11eb-84d8-6484e1c413e5.png)

Let me know if I can improve it.

**Comment by daniel-shuy** [comment]
Wow that was fast, its perfect, thanks!
